config/routes.rb
Rails.application.routes.draw do
  get 'help', to:'static_pages#help'
  get 'about', to:'static_pages#about'
  get 'login', to:'sessions#new'
  post 'login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'
  resources :users
  resources :personal_schedules, only:[:create, :edit, :update, :destroy]
  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/personal_schedule.rb
# == Schema Information
#
# Table name: personal_schedules
#
#  id         :integer          not null, primary key
#  content    :text
#  user_id    :integer
#  starts_at  :datetime
#  ends_at    :datetime
#  importance :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PersonalSchedule < ApplicationRecord
  belongs_to :user

  validates :user_id, presence:true
  validates :content, presence:true
  validates :starts_at, presence:true
  validates :ends_at, presence:true
  validates :importance, presence:true, inclusion: { in: 1..3 }
  validate :start_validate
  validate :time_validate

  def starts_at_format
    starts_at.strftime("%Y年%-m月%-d日%H:%M")
  end

  def ends_at_format
    ends_at.strftime("%Y年%-m月%-d日%H:%M")
  end

  private
    def time_validate
      if !starts_at.blank? && !ends_at.blank?
        if starts_at > ends_at
          errors.add(:starts_at, 'Invalid time duration.')
        end
      end
    end

    def start_validate
      if !starts_at.blank?
        if starts_at < Time.zone.now
          errors.add(:starts_at, 'Invalid start time.')
        end
      end
    end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  email           :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  has_many :personal_schedules, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :name, presence:true, length:{ maximum:30 }
  validates :email, presence:true, length:{ maximum:255 },
          format: { with:VALID_EMAIL_REGEX },
          uniqueness:{ case_sensitive:true }

  has_secure_password
  #パスワードは半角英数小文字、大文字、数字8~100
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)[a-zA-Z\d]{8,100}+\z/
  validates :password, presence:true,
          format: { with:VALID_PASSWORD_REGEX },
          allow_nil:true

  #ハッシュを渡す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost:cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
    def logged_in_user
      unless logged_in?
        flash[:danger] = 'Please login.'
        redirect_to login_url
      end
    end
end

app/controllers/personal_schedules_controller.rb
class PersonalSchedulesController < ApplicationController
  before_action :logged_in_user, only:[:create, :update, :destroy, :edit]
  before_action :is_mine?, only:[:update, :destroy, :edit]

  def create
    @schedule = current_user.personal_schedules.build(schedule_params)
    if @schedule.save
      flash[:success] = '登録完了!'
      redirect_to root_url
    else
      #@user = current_user
      #@personal_schedules = @user.personal_schedules.all.order('starts_at, importance')
      #render 'users/show'
      redirect_to user_url(current_user), flash: { error:@schedule.errors.full_messages }
    end
  end

  def edit
  end

  def update
    if @schedule.update_attributes(schedule_params)
      flash[:info] = '更新完了!'
      redirect_to root_url
    else
      redirect_to edit_personal_schedule_url(@schedule), flash: { error:@schedule.errors.full_messages }
    end
  end

  def destroy
    @schedule.destroy
    flash[:success] = '削除完了!'
    redirect_to user_url(current_user)
  end

  private
    def schedule_params
      params.require(:personal_schedule).permit(:content, :starts_at, :ends_at, :importance)
    end

    def is_mine?
      @schedule = PersonalSchedule.find(params[:id])
      @user = User.find(@schedule.user_id)
      unless current_user.id == @user.id
        flash[:danger] = '他人の予定いじるなや!'
        redirect_to user_url(current_user)
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email:params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      login user
      redirect_to user
    else
      flash.now[:danger] = 'Something wrong! Please log in again.'
      render 'new'
    end
  end

  def destroy
    logout
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @user = current_user
    end
  end

  def about
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  before_action :logged_in_user, only:[:index, :edit, :update, :destroy]
  before_action :same_user?, only:[:edit, :update, :destroy]

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url
    else
      render action: :new
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def show #scheduleのnewを兼ねる
    @user = User.find(params[:id])
    @schedule = current_user.personal_schedules.build
    @personal_schedules = @user.personal_schedules.all.order('starts_at, importance')
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile Updated'
      redirect_to @user
    else
      render 'users/edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'User deleted'
    redirect_to root_url
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def same_user?
      @user = User.find(params[:id])
      unless current_user == @user
        flash[:danger] = 'Invalid user.'
        redirect_to user_url(current_user)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/personal_schedules_helper.rb
module PersonalSchedulesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
  end

  def logout
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id:session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_head.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_header.html.erb
<header>
  <div class = 'container'>
    <% if logged_in? %>
      <%= render 'layouts/header_login' %>
    <% else %>
      <%= render 'layouts/header_not_login' %>
    <% end %>
</header>

app/views/layouts/_header_login.html.erb
<%# pc版用 %>
<div class = 'd-none d-md-block'>
  <nav class = 'navbar navbar-light bg-light navbar-expand-md fixed-top'>
    <%= link_to 'Meetupper(icon)', root_path, class:'navbar-brand' %>
    <ul class = 'navbar-nav ml-auto'>
      <li class = 'nav-item'>
        <%= link_to 'Schedule', @user, class:'nav-link' %>
      </li>
      <li class = 'nav-item'>
        <%= link_to 'Friends', '#', class:'nav-link' %>
      </li>
      <li class = 'nav-item'>
        <%= link_to 'Group Management', '#', class:'nav-link' %>
      </li>
      <li class = 'nav-item dropdown'>
        <a href = '#' class = 'dropdown-toggle nav-link' data-toggle = 'dropdown'>
          Settings
        </a>
        <div class = 'dropdown-menu dropdown-menu-right'>
          <%= link_to 'A', '#', class:'dropdown-item' %>
          <%= link_to 'B', '#', class:'dropdown-item' %>
          <%= link_to 'Log out', logout_path, class:'dropdown-item',
                                              method:'delete' %>
        </div>
      </li>
    </ul>
  </nav>
</div>

<%# スマホ用 %>
<div class = 'd-block d-md-none'>
  <nav class = 'navbar navbar-light bg-light navbar-expand fixed-top'>
    <%= link_to 'Meetupper(icon)', root_path, class:'navbar-brand' %>
  </nav>
</div>

app/views/layouts/_header_not_login.html.erb
<%# pc版用 %>
<div class = 'd-none d-md-block'>
  <nav class = 'navbar navbar-light bg-light navbar-expand-md fixed-top'>
    <%= link_to 'Meetupper(icon)', root_path, class:'navbar-brand' %>
    <ul class = 'navbar-nav ml-auto'>
      <li class = 'nav-item'>
        <%= link_to 'Log in', login_path, class:'nav-link' %>
      </li>
      <li class = 'nav-item dropdown'>
        <a href = '#' class = 'dropdown-toggle nav-link' data-toggle = 'dropdown'>
          Settings
        </a>
        <div class = 'dropdown-menu dropdown-menu-right'>
          <%= link_to 'Sign up', new_user_path, class:'dropdown-item' %>
          <%= link_to 'B', '#', class:'dropdown-item' %>
          <%= link_to 'C', '#', class:'dropdown-item' %>
        </div>
      </li>
    </ul>
  </nav>
</div>

<%# スマホ用 %>
<div class = 'd-block d-md-none'>
  <nav class = 'navbar navbar-light bg-light navbar-expand fixed-top'>
    <%= link_to 'Meetupper(icon)', root_path, class:'navbar-brand' %>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= render 'layouts/head' %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <main>
      <div class = 'container'>
        <% flash.each do |message_type, message| %>
          <div class = 'alert alert-<%= message_type %>'>
            <%= message %>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </main>

  </body>
</html>

app/views/personal_schedules/edit.html.erb
<% provide(:submit_message, '更新') %>
<% provide(:submit_path, personal_schedule_path(@schedule)) %>
<% provide(:submit_method, :patch) %>
<div class = 'container' id = 'schedule-edit'>
  <%= render 'shared/schedules_form' %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id = 'error_explanation'>
    <div class = 'alert alert-danger'>
      These contain <%= pluralize(object.errors.count, 'error') %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_schedule.html.erb
<div class = 'row'>
  <% @personal_schedules.each do |personal_schedule| %>
    <div class = 'container schedule'>
      <div class = 'd-flex'>
        <h2><%= personal_schedule.content %></h2>
        <div class = 'ml-auto align-self-center', id = 'buttons'>
          <%= link_to edit_personal_schedule_path(personal_schedule), class:'btn-sm btn-primary' do %>
            <span><%= fa_icon 'edit' %></span>
          <% end %>
          <%= link_to personal_schedule_path(personal_schedule), method:'delete', class:'btn-sm btn-primary' do %>
            <span><%= fa_icon 'trash' %></span>
          <% end %>
        </div>
      </div>
      <dl class = 'row'>
        <dt class = 'col-3'>開始時間</dt>
        <dd class = 'col-9'>
          <%= personal_schedule.starts_at_format %>
        </dd>

        <dt class = 'col-3'>終了時間</dt>
        <dd class = 'col-9'>
          <%= personal_schedule.ends_at_format %>
        </dd>

        <dt class = 'col-3'>重要度</dt>
        <dd class = 'col-1'>
          <% case personal_schedule.importance %>
          <% when 1 %>
            <span class = 'text-danger'>高</span>
          <% when 2 %>
            <span class = 'text-warning'>中</span>
          <% else %>
            <span class = 'text-info'>低</span>
          <% end %>
        </dd>
      </dl>
    </div>
  <% end %>
</div>

app/views/shared/_schedules_form.html.erb
<div class = 'row schedule-form'>
  <div class = 'col'>
    <%= form_for(@schedule) do |f| %>
      <% if flash[:error].present? %>
        <div id = 'error_explanation'>
          <div class = 'alert alert-danger'>
            These contain <%= pluralize(flash[:error].count, 'error') %>.
          </div>
          <ul>
            <% flash[:error].each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class = 'form-group row'>
        <%= f.label :content, '予定名', class:'col-md-2 col-form-label' %>
        <%= f.text_field :content, class:'form-control col-md-10' %>
      </div>

      <div class = 'form-group row'>
        <%= f.label :starts_at, '開始日時', class:'col-md-2 col-form-label' %>
        <%= f.datetime_select :starts_at, class:'form-control' %>
      </div>

      <div class = 'form-group row'>
        <%= f.label :ends_at, '終了日時', class:'col-md-2 col-form-label' %>
        <%= f.datetime_select :ends_at, class:'form-control' %>
      </div>

      <div class = 'form-group number-field row'>
        <%= f.label :importance, '重要度', class:'col-md-2 col-form-label' %>
        <%= f.number_field :importance, min:1, max:3, step:1 %>
      </div>

      <%= f.submit yield(:submit_message), class:'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/shared/_tmp_schedules_form.html.erb
<%# 予定作成画面 %>
<div class = 'row schedule-form'>
  <div class = 'col'>
    <%= form_for(:schedule, url:personal_schedules_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <div class = 'form-group'>
        <%= f.label :content, '予定名' %>
        <%= f.text_field :content, class:'form-control' %>
      </div>

      <div class = 'form-group'>
        <%= f.label :starts_at, '開始日時' %>
        <%= f.datetime_select :starts_at, class:'form-control' %>
      </div>

      <div class = 'form-group'>
        <%= f.label :ends_at, '終了日時' %>
        <%= f.datetime_select :ends_at, class:'form-control' %>
      </div>

      <div class = 'form-group number-field'>
        <%= f.label :importance, '重要度' %>
        <%= f.number_field :importance, min:1, max:3, step:1 %>
      </div>

      <%= f.submit '登録', class:'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Meetupper Webver') %>
<div class = 'container'>
  <h1>MeetUpper</h1>
  <% unless logged_in? %>
    <p>Welcome to MeetUpper! Please log in!</p>
  <% else %>
    <div class = 'container'>
      <div class ='row'>
        <div class = 'col-md-2'>
          group
        </div>
        <div class = 'col-md-3'>
          friends
        </div>
        <div class = 'col-md-7'>
          <div class = 'row'>
            <div class = 'col-md'>
              カレンダーがはいる
            </div>
          </div>
          <div class = 'row'>
            <div class = 'col-md'>
              予定の詳細
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_user_form.html.erb
<%= form_for @user do |f| %>
  <%= render 'shared/error_messages', object:f.object %>

  <div class = 'form-group'>
    <%= f.label :name %>
    <%= f.text_field :name, class:'form-control', placeholder:'Baka' %>
  </div>

  <div class = 'form-group'>
    <%= f.label :email %>
    <%= f.email_field :email, class:'form-control',
                              placeholder:'Aho.example.com'%>
  </div>

  <div class = 'form-group'>
    <%= f.label :password %>
    <%= f.password_field :password, class:'form-control' %>
  </div>

  <div class = 'form-group'>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class:'form-control' %>
  </div>

  <%= f.submit yield(:submit_message), class:'btn btn-primary' %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Change Profile') %>
<% provide(:submit_message, 'Update account') %>
<h1>Change profile</h1>
<div class = 'row'>
  <div class = 'col-md-6 offset-md-3'>
    <%= render 'user_form' %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<div>
  <% @users.each do |user| %>
    <%= user.name %>
    <%= user.email %>
    <br>
  <% end %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<% provide(:submit_message, 'Create Account') %>
<h1>New Account</h1>
<div class = 'row'>
  <div class = 'col-md-6 offset-md-3'>
    <%= render 'user_form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, 'Profile') %>
<% provide(:submit_message, '登録') %>
<% provide(:submit_path, personal_schedules_path) %>
<h1><%= @user.name %></h1>
<div class = 'container-fluid'>
  <%# 予定作成画面 %>
  <%= render 'shared/schedules_form' %>

  <%# 予定表示画面 %>
  <%= render 'shared/schedule' %>
</div>